/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package sportsrental;

/**
 *
 * @author Alex & Anna
 */
public class removeEmployee extends javax.swing.JFrame {

    /** Creates new form removeEmployee */
    public removeEmployee() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRemoveEmployee = new javax.swing.JButton();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        btnWelcomePage = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRemoveEmployee.setText("Remove Employee");
        btnRemoveEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblEmployeeID.setText("Employee ID:");
        getContentPane().add(lblEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 89, 20));

        btnWelcomePage.setText("Welcome Page");
        btnWelcomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWelcomePageActionPerformed(evt);
            }
        });
        getContentPane().add(btnWelcomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblMessage.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    private void btnRemoveEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveEmployeeActionPerformed
       //Get the employee ID from the text field
    String employeeIDText = txtEmployeeID.getText();

    //Check if the text field is empty
    if (employeeIDText.isEmpty()) {
        //Display an error message if the text field is empty
        lblMessage.setText("Please enter an Employee ID");
    } else {
        try {
            //Parse the employee ID to an integer
            int employeeID = Integer.parseInt(employeeIDText);

            //Create an instance of sportsRentalDB to access the removeEmployee method
            sportsRentalDB dbHelper = new sportsRentalDB();

            //Call the removeEmployee method with the employee ID
            dbHelper.removeEmployee(employeeID);

            //Display a success message
            lblMessage.setText("Employee removed successfully.");
        } catch (NumberFormatException e) {
            //Display an error message if the entered text is not a valid integer
            lblMessage.setText("Invalid Employee ID format.");
        }
    }
    }//GEN-LAST:event_btnRemoveEmployeeActionPerformed

    private void btnWelcomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWelcomePageActionPerformed
            this.dispose();
            WelcomePage wpage = new WelcomePage();
            wpage.setVisible(true);
    }//GEN-LAST:event_btnWelcomePageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removeEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoveEmployee;
    private javax.swing.JButton btnWelcomePage;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtEmployeeID;
    // End of variables declaration//GEN-END:variables

}
