/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sportsrental;

/**
 *
 * @author Alex & Anna
 */
public class removeCustomer extends javax.swing.JFrame {

    /**
     * Creates new form removeCustomer
     */
    public removeCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerID = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        btnRemoveCustomer = new javax.swing.JButton();
        btnWelcomePage = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCustomerID.setText("Customer ID");

        btnRemoveCustomer.setBackground(new java.awt.Color(153, 0, 153));
        btnRemoveCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveCustomer.setText("Remove Cutomer");
        btnRemoveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCustomerActionPerformed(evt);
            }
        });

        btnWelcomePage.setBackground(new java.awt.Color(0, 0, 0));
        btnWelcomePage.setForeground(new java.awt.Color(255, 255, 255));
        btnWelcomePage.setText("Back");
        btnWelcomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWelcomePageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWelcomePage)
                    .addComponent(btnRemoveCustomer)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCustomerID)
                        .addGap(38, 38, 38)
                        .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerID)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoveCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnWelcomePage)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCustomerActionPerformed
           //Get the text from the txtCustomerID field
            String customerIDText = txtCustomerID.getText().trim();

            //Check if the customerIDText is empty
            if (customerIDText.isEmpty()) {
                //Display an error message in lblMessage
                lblMessage.setText("Please enter a Customer ID.");
            } else {
                try {
                    //Parse the customerIDText to an integer
                    int customerID = Integer.parseInt(customerIDText);

                    //Call the removeCustomer method from sportsRentalDB and pass the customer ID
                    sportsRentalDB dbHelper = new sportsRentalDB();
                    dbHelper.removeCustomer(customerID);

                    //Display success message in lblMessage
                    lblMessage.setText("Customer removed successfully.");
                } catch (NumberFormatException e) {
                    //Display an error message in lblMessage if customerIDText is not a valid number
                    lblMessage.setText("Please enter a valid Customer ID.");
                }
            }
    }//GEN-LAST:event_btnRemoveCustomerActionPerformed

    private void btnWelcomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWelcomePageActionPerformed
            this.dispose();
            customerInfo infoCus = new customerInfo();
            infoCus.setVisible(true);
    }//GEN-LAST:event_btnWelcomePageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removeCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removeCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removeCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removeCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removeCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoveCustomer;
    private javax.swing.JButton btnWelcomePage;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtCustomerID;
    // End of variables declaration//GEN-END:variables
}
